<?php

namespace Database\Seeders;

use App\Models\Produto;
use App\Models\User;
use App\Models\Evento;
use Illuminate\Database\Seeder;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usuInclusao = User::first()?->id ?? 1;
        $eventoId = Evento::first()?->idt_evento;

        if (! $eventoId) {
            throw new \Exception('É necessário ter ao menos um Evento criado no banco para rodar o ProdutoSeeder.');
        }

        $produtos = [
            [
                'nom_produto' => 'PAULUS - YOUCAT - CATECISMO JOVEM DA IGREJA CATOLICA 1 Ed 2017',
                'des_produto' => 'Código: 9788534946575',
                'val_preco' => 44.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CNBB - CATECISMO DA IGREJA CATOLICA - PEQUENO - 5 EDICAO - NOVO DESIGN 5 Ed',
                'des_produto' => 'Código: 9786559750818',
                'val_preco' => 79.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'KEMPIS - IMITACAO DE CRISTO 1 Ed 2015',
                'des_produto' => 'Código: 9788532649829',
                'val_preco' => 19.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CRUZ - NOITE ESCURA SEM ORELHAS',
                'des_produto' => 'Código: 9788532670984',
                'val_preco' => 18.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'JESUS - HISTORIA DE UMA ALMA 1 Ed 2024',
                'des_produto' => 'Código: 9788532666246',
                'val_preco' => 27.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'EDITORA CULTOR DE LI - SELETA DE ORACOES 1 Ed 2010',
                'des_produto' => 'Código: 9788562219108',
                'val_preco' => 52.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'SANTA TERESINHA DO M - CHUVA DE ROSAS: ORACOES DE UMA ALMA DEVOTA 1 Ed 2025',
                'des_produto' => 'Código: 9788532671202',
                'val_preco' => 16.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'SANTA TERESINHA DO M - VIVER DE AMOR 1 Ed 2025',
                'des_produto' => 'Código: 9788532671196',
                'val_preco' => 13.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'JOULIN - TERESINHA DE JESUS: TRACOS BIOGRAFICOS 8 Ed 2010',
                'des_produto' => 'Código: 9788535626254',
                'val_preco' => 24.80,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'SANTA TERESA DE JESU - CAMINHO DE PERFEICAO 1 Ed 1998',
                'des_produto' => 'Código: 9788534911801',
                'val_preco' => 51.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ZANDONA - CURAR E RESTAURAR O MASCULINO: UMA JORNADA PELA CURA DA MASCULINI',
                'des_produto' => 'Código: 9786586698022',
                'val_preco' => 41.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'AQUINO - PROBLEMAS NO NAMORO 5 Ed 2010',
                'des_produto' => 'Código: 9788588158481',
                'val_preco' => 26.50,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'GAVIOLI - NAMORO: EM BUSCA DO VERDADEIRO AMOR 1 Ed 2020',
                'des_produto' => 'Código: 9788553392155',
                'val_preco' => 32.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ROGERIO - NAMORO SIM, BAGUNCA NAO 4 Ed 2006',
                'des_produto' => 'Código: 8572008667',
                'val_preco' => 49.80,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ZANDONA - LIBERTACAO DA MENTE ANSIOSA, A 1 Ed 2020',
                'des_produto' => 'Código: 9788594630711',
                'val_preco' => 28.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'MENDES - COMO SE DAR BEM COM QUEM VOCE QUER BEM 20 Ed 2016',
                'des_produto' => 'Código: 9788576776840',
                'val_preco' => 39.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'BONDAN - MAIS BELAS ORACOES ESCRITAS POR GRANDES MULHERES, AS 1 Ed 2022',
                'des_produto' => 'Código: 9786557134481',
                'val_preco' => 40.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'Albares - GUIA JOVEM DA BIBLIA 1 Ed 2025',
                'des_produto' => 'Código: 9788534956932',
                'val_preco' => 43.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'BELLA ARTE - MARCA PAGINA MENSAGENS E ORACOES DIVERSAS',
                'des_produto' => 'Código: 9793623002926',
                'val_preco' => 1.80,
                'qtd_produto' => 60,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA MADEIRA/HEMATITA/CRISTAL CORES VARIADAS NS DAS GRACAS',
                'des_produto' => 'Código: 9793605039445',
                'val_preco' => 12.00,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO TERCO 025 NSRA APARECIDA PRATEADO C/ STARSS 5CM REF 6X1-20',
                'des_produto' => 'Código: 9793605014251',
                'val_preco' => 13.00,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO JESUS MISERICORDIOSO METAL REF 6X1-55',
                'des_produto' => 'Código: 9793605044906',
                'val_preco' => 12.90,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO 025 CRUCIFIXO C/ MEDALHA SAO BENTO DOURADO REF 1X1-142',
                'des_produto' => 'Código: 9793605065062',
                'val_preco' => 12.00,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO SAO JOSE MAD. IMBUIA C/ MEDALHA C/FOTO PROT.E PAI REF. SJ022-1',
                'des_produto' => 'Código: 7899920552194',
                'val_preco' => 18.40,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO DEZENA MADEIRA IMBUIA SAO CARLO ACUTIS REF.CL023',
                'des_produto' => 'Código: 7899920544571',
                'val_preco' => 19.90,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO NSA SRA APARECIDA MANTO AZUL STRSS 4X1-74 / 5X1-6',
                'des_produto' => 'Código: 9793605038530',
                'val_preco' => 12.00,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CHAVEIRO 025 BORRACHA SANTOS VAR F1301697 1301698 1301699 1301700 1301705 1',
                'des_produto' => 'Código: 8600013016986',
                'val_preco' => 4.50,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'TERÇO PULSEIRA MADEIRA PRETA, VERMELHA E PEROLA 03 MM TE-86, TE-87, TE-89',
                'des_produto' => 'Código: 9790090025014',
                'val_preco' => 17.90,
                'qtd_produto' => 10,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA TERCO PULSO CRISTAL SAO BENTO',
                'des_produto' => 'Código: 9793605036826',
                'val_preco' => 16.90,
                'qtd_produto' => 10,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA CORRENTE 5 CONTAS PEROLA 5 CONT FOSCAS 9 NSR APARECIDA DOURADA',
                'des_produto' => 'Código: 3605000170660',
                'val_preco' => 15.50,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'DEZENA MAD.ENCERADA SEM O AGELUS CRUZ COM CRISTO REF. DE-08',
                'des_produto' => 'Código: 9793605039988',
                'val_preco' => 6.90,
                'qtd_produto' => 10,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'DEZENA CARRO IRIZADO 10MM O.V. REF 304',
                'des_produto' => 'Código: 7899920424156',
                'val_preco' => 17.90,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA DEZENA MADEIRA IMBUIA 8/11MM SAO BENTO REF 166748 ARAMON',
                'des_produto' => 'Código: 7899347263819',
                'val_preco' => 14.50,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA 025 HEMATITA/ CRISTAL VARIADAS MEDALHA REF 1X21-45 8X1-64',
                'des_produto' => 'Código: 9793605039476',
                'val_preco' => 12.00,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'DEZENA 025 CARRO FURTA COR ESPIRITO SANTO DOURADO 2X1-72',
                'des_produto' => 'Código: 9793605038769',
                'val_preco' => 26.00,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'AVE MARIA SHOPPING - DEZENA 025 GLAMOUR PEROLADA SAO BENTO RESINADO 12MM RE',
                'des_produto' => 'Código: 9793605013827',
                'val_preco' => 24.00,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'TERCO COM FOLHETO COROA DAS LAGRIMAS 8MM 6158',
                'des_produto' => 'Código: 7898485031571',
                'val_preco' => 14.90,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'TERCO 025 PERFUMADO ENTREMEIO SAO BENTO/APARECIDA 6MM REF 7X3-16 7X3-17',
                'des_produto' => 'Código: 9793605013698',
                'val_preco' => 15.00,
                'qtd_produto' => 20,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'AVE MARIA SHOPPING - TERCO 025 PERFUMADO 6MM MEDALHA DE SAO BENTO REF 4X29-',
                'des_produto' => 'Código: 9793605014755',
                'val_preco' => 12.00,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'TERCO 025 HEMATITA 8MM ENTREMEIO NSA APARECIDA REF 7X3-11',
                'des_produto' => 'Código: 9793605038547',
                'val_preco' => 32.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'TERCO PLASTICO QUADRADO GRANDE TG01 VARIAS CORES LEITOSO E TRANSPARENTE SAN',
                'des_produto' => 'Código: 9790090003821',
                'val_preco' => 1.80,
                'qtd_produto' => 72,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'APARECIDA 025 ADESIVO METAL COM STRASS METAL DOURADA REF 5X1-99 1 Ed 2020',
                'des_produto' => 'Código: 9793623003435',
                'val_preco' => 20.00,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'IMAGEM METAL P/PAINEL SAO MIGUEL -OV REF 228102405',
                'des_produto' => 'Código: 2500000143816',
                'val_preco' => 17.90,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ADORNO NS APARECIDA METAL OURO VELHO COM BASE 10CM OURO REF 9981OVBASE',
                'des_produto' => 'Código: 42882767657',
                'val_preco' => 74.00,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ADORNO NOSSA SENHORA APARECIDA EM METAL PRATA VELHA 12CM 20210PV 040',
                'des_produto' => 'Código: 9793605034389',
                'val_preco' => 89.50,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ADORNO 025 OSTENSORIO DOURADO ADESIVO CARRO REF 4X1-62 7X1-14 1X1-139 2018',
                'des_produto' => 'Código: 9793605076327',
                'val_preco' => 18.00,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'IMAGEM DE METAL PARA PAINEL MEDALHA DE SAO BENTO OV 2283032-05',
                'des_produto' => 'Código: 2500000143526',
                'val_preco' => 19.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ESCAPULARU PANO NSA SRA DO CARMO 40MM REF.2295007-00',
                'des_produto' => 'Código: 2500000144608',
                'val_preco' => 21.90,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CRUCIFIXO DE MADEIRA 07CM IMBUIA MESA E PAREDE O.V REF CX001',
                'des_produto' => 'Código: 7899920022789',
                'val_preco' => 14.50,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CAPELA ORATORIO MDF 13CM 05070 040',
                'des_produto' => 'Código: 50708',
                'val_preco' => 23.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ENFEITE INFANTIL DE MDF 10CM SANTOS VARIADOS',
                'des_produto' => 'Código: 9793605048294',
                'val_preco' => 8.90,
                'qtd_produto' => 8,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA DEZENA ACO INOX REF PI07 SOTILLE JOIAS',
                'des_produto' => 'Código: 9793605001190',
                'val_preco' => 18.50,
                'qtd_produto' => 10,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'IMAGEM SANTA TEREZINHA RESINA 8CM REF YFSTCBM',
                'des_produto' => 'Código: 4894290395627',
                'val_preco' => 35.50,
                'qtd_produto' => 6,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'QUADRO DE MESA DOMO75MM MDF JESUS MISERICORDIOSO REF.226300400',
                'des_produto' => 'Código: 9793623003145',
                'val_preco' => 7.50,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ENFEITE PARA MESA MDF RESINADO SANTOS VARIADOS 15CM REF.70245',
                'des_produto' => 'Código: 9793605040953',
                'val_preco' => 39.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'SANTOS DE MESA MDF SILHETA SANTOS VARIADOS REF.3769',
                'des_produto' => 'Código: 9793605048959',
                'val_preco' => 13.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ADORNO DE MESA CAPELA SANTOS VARIADOS 14X10CM',
                'des_produto' => 'Código: 9793605049284',
                'val_preco' => 19.90,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CAPA DE CELULAR PERSONALIZADA MODELOS DIVERSOS REF 002',
                'des_produto' => 'Código: 9793605029798',
                'val_preco' => 35.00,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'GARGANTILHA MEDALHA REDONDA ESPIRITO SANTO ACO INOX NSA 1 Ed 2020',
                'des_produto' => 'Código: 3605000179915',
                'val_preco' => 24.00,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ESCAPULARIO 025 MEDIO INOX BORDA CHANFRADA 02-035 1 Ed 2020',
                'des_produto' => 'Código: 9793605056961',
                'val_preco' => 19.90,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'GARGANTILHA CORRENTE GROSSA SAO BENTO AUTO RELEVO INOX NSA 1 Ed 2020',
                'des_produto' => 'Código: 9793605012967',
                'val_preco' => 24.00,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ESCAPULARIO 025 INOX MARCISO QUADRADO MEDIO',
                'des_produto' => 'Código: 9793605000124',
                'val_preco' => 19.90,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'COLAR INOZ PIGENTE CRUZ C/ CRISTO REF 88',
                'des_produto' => 'Código: 3605000157999',
                'val_preco' => 17.00,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'GARGANTILHA 025 DOURADA MEDALHA SAO BENTO MEDIA GRAVADO',
                'des_produto' => 'Código: 3605000170615',
                'val_preco' => 19.90,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'GARGANTILHA INOX MEDALHA SAO BENTO PQNA GORDA NSA',
                'des_produto' => 'Código: 3605000141172',
                'val_preco' => 19.90,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ADESIVO PARA CARRO PLISMATICO MEDIO SILENCIO REF AD002-2',
                'des_produto' => 'Código: 7898622796776',
                'val_preco' => 9.90,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'AVE MARIA SHOPPING - ADESIVO DE SAO BENTO RESINADO GRANDE BRANCO AR047-1 1',
                'des_produto' => 'Código: 7899927169623',
                'val_preco' => 25.50,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'MEDALHA 025 SAO BENTO 2,6 X 2,6 CM NIQUEL/OURO VELHO CORDAO 183',
                'des_produto' => 'Código: 9790090009366',
                'val_preco' => 7.50,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'CORDAO C/TAU MAD.LISA REF. CO003',
                'des_produto' => 'Código: 7898622791443',
                'val_preco' => 6.90,
                'qtd_produto' => 4,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'PULSEIRA 025 TERCO MICANGA 6MM NS APARECIDA C/ CRUZ REF 8X1-24 6X1-82',
                'des_produto' => 'Código: 9793605014015',
                'val_preco' => 10.90,
                'qtd_produto' => 3,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ALMOFADA NANINHAS TAM MEDIA COLECAO REF 3000 30191052/21901 DIMER',
                'des_produto' => 'Código: 7890876730605',
                'val_preco' => 41.50,
                'qtd_produto' => 5,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'SEM AUTOR - COLORIR E REZAR COM OS SANTOS E SANTAS',
                'des_produto' => 'Código: 9788532672759',
                'val_preco' => 26.00,
                'qtd_produto' => 2,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'ERLIN, - HISTORIA DE JESUS, A - TURMA DA MONICA 1 Ed 2024',
                'des_produto' => 'Código: 9786557070987',
                'val_preco' => 59.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
            [
                'nom_produto' => 'LUIS ERLIN - MINHA PRIMEIRA BIBLIA (GRANDE)',
                'des_produto' => 'Código: 9788527613323',
                'val_preco' => 59.90,
                'qtd_produto' => 1,
                'ind_favorito' => false,
                'usu_inclusao' => $usuInclusao,
            ],
        ];

        foreach ($produtos as $p) {
            $p['idt_evento'] = $eventoId;
            Produto::updateOrCreate(
                ['nom_produto' => $p['nom_produto']],
                $p
            );
        }
    }
}
